import yaml from "js-yaml";

const targetFramework = "net10.0";

const platformStepsGen = (name: string, rid: string, platform: string) => [
  {
    name: `Build ${name}`,
    if: `matrix.platform == '${platform}'`,
    run: `dotnet publish --configuration Release -r ${rid}`,
  },
  {
    name: `Upload ${name} artifacts`,
    if: `matrix.platform == '${platform}'`,
    uses: "actions/upload-artifact@v4",
    with: {
      name: `efmig-${name}-Release`,
      path: `Efmig/bin/Release/${targetFramework}/${rid}/publish/`,
      "if-no-files-found": "error",
    },
  },
];

const platformConfigs = [
  { name: "win-x64", rid: "win-x64", platform: "windows-latest" },
  { name: "win-arm64", rid: "win-arm64", platform: "windows-latest" },
  { name: "linux-x64", rid: "linux-x64", platform: "ubuntu-latest" },
  { name: "linux-arm64", rid: "linux-arm64", platform: "ubuntu-latest" },
  { name: "osx-x64", rid: "osx-x64", platform: "macos-latest" },
  { name: "osx-arm64", rid: "osx-arm64", platform: "macos-latest" },
];

const extraSteps = platformConfigs.flatMap((config) =>
  platformStepsGen(config.name, config.rid, config.platform)
);

const workflow = {
  name: "build",
  on: {
    push: {
      branches: ["master"],
    },
    pull_request: {
      branches: ["master"],
    },
  },
  jobs: {
    build: {
      strategy: {
        matrix: {
          platform: ["ubuntu-latest", "macos-latest", "windows-latest"],
        },
      },
      "runs-on": "${{ matrix.platform }}",
      steps: [
        {
          uses: "actions/checkout@v3",
        },
        {
          name: "Setup .NET Core SDK ${{ matrix.dotnet-version }}",
          uses: "actions/setup-dotnet@v5",
          with: {
            "dotnet-version": "10.0.x",
          },
        },
        ...extraSteps,
      ],
    },
  },
};

const yamlContent =
  "# Auto-generated by workflowgen.ts\n" +
  "# Do not edit manually.\n\n" +
  yaml.dump(workflow, { lineWidth: -1, noRefs: true });

Deno.writeTextFile("../.github/workflows/build.yml", yamlContent);
